### PR TITLE
Styling fixes and group badge on tabbar

### LINKED ISSUE #136: Color theme white
Stoopid me changed the color theme from orange to white cause it looked nicer in some places. However,  the result is that some things aren't visible anymore like the checkboxes on the user page and also the close text in the pickers.

### LINKED ISSUE #143: Notification on nav plz
There should be a notification icon on the nollning icon in the nav. Big mistake. Fix plz.

### PR DESCRIPTION
**Pull request by FredrikLastow**
- Adds a badge to the tabbar that shows the unread message count (closes #143) 
- Fixes the color theme white problem
- Adds an external link to the F-wiki
- Sets the statusbar colors to be the same for both iOS and Android
- Removes unnecessary timeouts in `adventures.js` that waited for a fade out. Now the content just gets cleared and fades in slower
- Closes #136

### CODE REVIEW

File: www/js/adventures.js [hunk 1]
```diff
@@ -360,19 +355,14 @@ $$(document).on('page:init', '.page[data-name="adventures"]', function (e) {
...
+          page.find('.adventures-highscore-list').html('');
 
-          // Wait for old content to fade out
-          setTimeout(function() {
-            // Generate the template HTML and fade it in in the highscore list
-            const templateHTML = app.templates.adventuresHighscoreTemplate(highscoreData);
-            $(templateHTML).hide().appendTo('.adventures-highscore-list').fadeIn(300);
+          // Generate the template HTML and fade it in in the highscore list
+          const templateHTML = app.templates.adventuresHighscoreTemplate(highscoreData);
+          $(templateHTML).hide().appendTo('.adventures-highscore-list').fadeIn(600);
```
Comment (olofenglund96) [inline www/js/adventures.js]: Maybe change to 300 ms
