### PR TITLE
Fix bug where custom food preferences was not saved to user

### LINKED ISSUE #216: Custom food preferences is not saved to user
If a user updates its custom food preferences in the app, it is not properly saved to the user.

### PR DESCRIPTION
**Pull request by davidkrantz**
- Fix bug where custom food preferences was not saved to user by adding the `food_custom` option to the form that is used to update the user.
- Fix bug that occurred if food preferences only contained the custom food preferences.
- If the custom food preferences only contains whitespaces, it will now not be interpreted as an actual food preference.
- Closes #216.

### CODE REVIEW

File: www/js/user_page.js [hunk 1]
```diff
@@ -308,7 +310,9 @@ function initUserPage() {
       // If it's an array (either switch or food preferences)
       if (typeof value === 'object') {
         if (key == 'food_preferences') {
-          if (value.length != 0) {
+          if (value.length === 0 || value.length === 1 && value[0] === 'Annat') {
```
Comment (FredrikLastow) [inline www/js/user_page.js]: When does it occur that the only value of `food_preferences` is `Annat`? When I test locally I can never get `Annat` to appear in the array. Am I missing something? If this is true and I'm not just stupid the else statement can be shortened as well.

File: www/js/user_page.js [hunk 2]
```diff
@@ -329,6 +331,7 @@ function initUserPage() {
       }
       user[key] = value;
     }
+    formData['food_custom'] = foodCustom;
```
[the remark this answers is not in the document]
Comment (FredrikLastow) [reply www/js/user_page.js]: What he said

File: www/js/user_page.js [hunk 3]
```diff
@@ -273,12 +275,12 @@ function initUserPage() {
...
 
-      // Update custom food data
-      $.auth.user.food_custom = foodCustom;
-
-      // Edit and update formData and the user object
+      // Edit and update formData
       formData = prepareFormData(formData, user);
 
+      // Update custom food data to local user variable
+      user.food_custom = foodCustom;
```
Comment (FredrikLastow) [inline www/js/user_page.js]: I think it's better to move this to `prepareFormData()` where the rest of the local user object is updated

File: www/js/user_page.js (hunk 1 above)
Comment (davidkrantz) [reply www/js/user_page.js]: If `Annat` is specified in the app then before `prepareFormData` it is included in the `food_preferences` array. The additional check to see if `Annat` is the only element in the array is needed in the case that you have `Annat` and one more food preferences, and then remove this other preferences. Previously, this other preferences would not be removed from the user in this case.

Comment (FredrikLastow) [reply www/js/user_page.js]: Okay, sounds good!
