### PR TITLE
general bug fixes and improvements

### LINKED ISSUE #60: Status text when no nofications/groups are available
After notfications and groups are loaded there should be information if there was nothing to load, instead of the page being just empty. An empty page can be interpreted as it's not done loading yet or that something just went wrong.

### LINKED ISSUE #61: Event page information arrow
On certain events the information arrow is over the text.

### LINKED ISSUE #62: Group information on event signup
img_5724

### PR DESCRIPTION
**Pull request by FredrikLastow**
closes #60
closes #61 
closes #62 
Fixes bug with the notification tab not updating after logout

### CODE REVIEW

File: www/js/event.js [hunk 1]
```diff
@@ -380,7 +379,7 @@ function updateSignupContent(eventData){
 
           groupContainer.find('#event-signup-groupname').html('');
         }else{
-          groupContainer.removeClass('hidden');
+          groupContainer.find('#event-signup-groupname').html('');
```
Comment (navro) [inline www/js/event.js]: No need to run `groupContainer.find('#event-signup-groupname').html('')` twice
